title: プログラミング, ときどき...
author: Yasuharu Iida

lang: ja
timezone: Asia/Tokyo

exclude:
  - README.md
  - docker-compose.yml

theme: jekyll-theme-cayman
github:
  is_project_page: false

google_analytics: UA-145256426-2

parmalink: date
