version: "3"
services:
  jekyll:
    image: jekyll/jekyll:pages
    command: jekyll serve --watch --force_polling
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - 4000:4000
